apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.6
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-controller
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
